name: pathfinding
author: pavelgj@gmail.com
homepage: https://github.com/pavelgj/PathFinding.dart
version: 0.0.2
description: A Dart port of https://github.com/qiao/PathFinding.js library
dev_dependencies:
  unittest: any
